# source('~/covid/r/code.r')
source('~/COVID-19-RCT-STAT-TOOLS/Simulation/time-to-event/rmst/r/code.r')
task_id = Sys.getenv("SLURM_ARRAY_TASK_ID")
## sink(file = paste('log', task_id, '.txt', sep=''))
try(assign(paste('r', task_id, sep = ''), try(funslave(as.numeric(task_id)))))
## sink()
save.image(paste('/fh/scratch/delete30/gao_f/mbannick/tte-output/rmst/out/out', task_id, '.rda', sep = ''))
quit('no')
